name: Discord Reminder Bot

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"오늘 푼 문제를 업로드하세요.\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
